name: Stats

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run script
        run: |
          curl -O https://raw.githubusercontent.com/mouredev/roadmap-retos-programacion/main/Roadmap/stats.py
          python stats.py
      
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_messages: Update stats
          commit_user_name: sigridveronica [Github Actions]
          commit_user_email: sigridveroncia@gmail.com
          commit_author: sigridveronica

       
      
